name: AzureSpringApps

on:
  workflow_dispatch:
  push:
env:
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}/frontend
  AZURE_SUBSCRIPTION: 6f25a7f4-92bb-440a-a21e-1cbae174dc04
  AZURE_WEBAPP_NAME: sb1-appui
  NODE_VERSION: '20.x'                # set this to the node version to use


jobs:
  deploy_to_production:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install --verbose
        npm run build --if-present
        npm run test --if-present
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using credentials'
      uses: azure/webapps-deploy@v3
      with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
