name: Build and Deploy to Azure 

on:
  workflow_dispatch:
  push:
env:
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}/frontend/
  AZURE_SUBSCRIPTION: 6f25a7f4-92bb-440a-a21e-1cbae174dc04
  AZURE_WEBAPP_NAME: sb1-appui
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read
defaults:
 run:
  working-directory: './frontend/'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: './frontend/'